### ISSUE TITLE
LVGL conditional compliation

### ISSUE THREAD

**Issue by jonsmirl** [XuNeo/luavgl#25]
### Introduce the problem

FYI issue for the future. I had a lot of widgets selectively turned off in LVGL to save RAM on my device. I had to turn a bunch of them back on since Luavgl didn't compile with them turned off. For example I don't need a keyboard and textarea but I had to turn them back on because Luavgl didn't support having them off.  This is no big deal, when I get back to minimizing RAM I can #ifdef luavgl as needed for my use case.

things like this....
CONFIG_LV_USE_ROLLER=y
CONFIG_LV_USE_KEYBOARD=y
CONFIG_LV_USE_TEXTAREA=y

BTW, I am using Luavgl with NodeMCU on an ESP32S3 with an RGB LCD.

**Comment by XuNeo** [comment]
Thank you for the feedback. Now those widgets should be able to turn off independently, except for Image and Label.

Please do not hesitate post issues you met, I'd more than happy to help. Thanks.
