### ISSUE TITLE
Macros for rotable

### ISSUE THREAD

**Issue by jonsmirl** [XuNeo/luavgl#28]
### Introduce the problem

NodeMCU has made some interesting macros which might be worth copying.
https://github.com/nodemcu/nodemcu-firmware/blob/release/app/lua53/lnodemcu.h
example use:
https://github.com/nodemcu/nodemcu-firmware/blob/release/app/modules/i2c.c#L149

NodeMCU doesn't need a file like lvgl.lua. I don't know enough about Lua yet to understand why or which way is better.

**Comment by XuNeo** [comment]
Thank you for the feedback. The rotable does reduce RAM consumption a lot. Similar implementation here: https://github.com/siffiejoe/lua-rotable.

The lvgl.lua file is meant for linting only. It could work with vscode extension emmylua.
