### ISSUE TITLE
Drawing API?

### ISSUE THREAD

**Issue by jonsmirl** [XuNeo/luavgl#34]
### Introduce the problem

I don't see any way to construct an image, either draw_ctx or canvas. I need to construct RGB and HSL spectrum gradient bitmaps. I can make them in C and pass back to Lua, but do you have plans for a drawing API?

**Comment by jonsmirl** [comment]
I wrote some test code in C, this isn't working out very well on my small LCD so I may drop generating bitmaps.

**Comment by XuNeo** [comment]
I image it could be achieved by generating data from lua and use those data as source of image widget. The image header needs to be added though. I have never tested this way.

Another method would be develop a custom widget that do the magic work from C. The example widget locates in `simulator/widgets`.
