### ISSUE TITLE
add more documents

### ISSUE THREAD

**Issue by xueliu** [XuNeo/luavgl#6]
Hello Xu,

Thanks for your great work.

Can you add more information about how to prepare the lvgl environment ?

I remember that the luavgl library should be a dynamic library (.so file). so lua can find it when **local lvgl = require("lvgl")**. 
It it right ?

**Comment by XuNeo** [comment]
Yes. 
Currently, `luavgl` mainly targets for embedded devices, thus no `.so` file needed. Following the method in simulator, we can simply register `lvgl` module to lua by calling `luaL_requiref`.

**Comment by xueliu** [comment]
The `embedded devices` means micro controller not embedded Linux device like raspberry pi. Is it right ?

**Comment by XuNeo** [comment]
Yes. For raspberry pi, the simulator provided can run out of box.
