### ISSUE TITLE
I want to use Lua in lvgl vs

### ISSUE THREAD

**Issue by jinsc123654** [XuNeo/luavgl#9]
There were many errors in vs
Lua lvgl doesn't seem to be a standard C language
![VeryCapture_20240117155330](https://github.com/XuNeo/luavgl/assets/53360341/f822310c-9fa6-4be2-8748-fa124e54918b)
![VeryCapture_20240117155608](https://github.com/XuNeo/luavgl/assets/53360341/9654aaaa-e39b-422b-8cae-54710817abb4)

**Comment by XuNeo** [comment]
It's a C99 standard to define variable length of array on stack.
See https://stackoverflow.com/questions/26441916/dynamic-array-allocation-on-stack-in-c

Are you able to get lvgl v8.3 simulator up and running?

**Comment by jinsc123654** [comment]
The lvgl simulator can run.
Variable length arrays seem to not be usable in vs.
